
== Chapter 3

[%unbreakable]
====
wiles

Cunning tricks to get something.
====

[%unbreakable]
====
courtesan

A prostitute.
====

[%unbreakable]
====
wellspring

A source of continual supply.
====

[%unbreakable]
====
goaded

To provoke or annoy someone.
====

[%unbreakable]
====
infallible

Incapable of making mistakes.
====

[%unbreakable]
====
heredity

Passing qualities from parents to children.
====

[%unbreakable]
====
flotsam

Floating remains of a shipwreck.
====

[%unbreakable]
====
facetious

Inappropriate humor for a serious situation.
====

[%unbreakable]
====
monopoly

The exclusive control of a service or commodity.
====

[%unbreakable]
====
interstellar

Existing between stars.
====

[%unbreakable]
====
conflagration

A large destructive fire.
====

[%unbreakable]
====
proctor

A supervisor of students.
====

[%unbreakable]
====
wryly

Express mocking humor.
====

[%unbreakable]
====
bandy

Argue pointlessly.
====

[%unbreakable]
====
willow

A type of tree with pliant branches.
====

[%unbreakable]
====
buffet

To strike with force.
====

[%unbreakable]
====
fatuous

Silly and pointless.
====

[%unbreakable]
====
platitudes

A statement that is used too often to be interesting.
====

[%unbreakable]
====
seethed

To show strong emotion.
====

[%unbreakable]
====
unnerving

Causing anxiety or fear.
====
